name: Generate docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/Microsoft.Sbom.Api/Config/Args/*.cs'
      - 'src/Microsoft.Sbom.Common/Config/IConfiguration.cs'

permissions:
  contents: write

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0

      - name: Generate docs
        run: |
          # Run CLI
          dotnet run -p src/Microsoft.Sbom.Tool generate -- -h 2> help.txt || true
          cat <<EOF > docs/sbom-tool-arguments.md
          # Sbom tool arguments
          
          \`\`\`shell
          dotnet run -p './src/Microsoft.Sbom.Tool' generate -- -h
          \`\`\`

          \`\`\`
          $(tail --lines=+4 help.txt)
          \`\`\`
          EOF

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 'Auto update docs/*.md'
          file_pattern: 'docs/*.md'
          